---

- name: Download the percona repo package
  copy: 
        src: percona-release_0.1-6.bionic_all.deb
        dest: /tmp

- name: Install the percona repo package
  apt:
     deb: /tmp/percona-release_0.1-6.bionic_all.deb
     state: present

- name: Specify MySQL root password before installing
  debconf: name='mysql-server' question='percona-server-server-5.7/root-pass' value='root' vtype='password'
  become: true

- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='percona-server-server-5.7/re-root-pass' value='root' vtype='password'
  become: true

- name: Install packages for PS 5.7
  apt:
    state: latest
    name: "{{ item.value }}"
    update_cache: yes 
  with_items:
          - value: percona-toolkit
          - value: percona-server-server-5.7
          - value: percona-server-client-5.7 
          - value: sysbench

- name: copy the configuration template
  template:
    src: templates/my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  register: mysql_config

- name: restart MySQL if config changed
  systemd:
          name: mysql
          state: restarted
  when: mysql_config.changed

- name: Copy the .my.cnf file for the ubuntu user
  copy:
          src: .my.cnf
          dest: /home/ubuntu/.my.cnf
          owner: ubuntu
          group: ubuntu

- name: Create the orchestrator user
  shell: mysql --defaults-file=/home/ubuntu/.my.cnf -e "create user IF NOT EXISTS orchestrator@'%' identified by 'orc_topology_password'"

- name: Set the grants for the orchestrator user 
  shell: mysql --defaults-file=/home/ubuntu/.my.cnf -e "GRANT SUPER, PROCESS, REPLICATION SLAVE, REPLICATION CLIENT, RELOAD ON *.* TO 'orchestrator'@'%';create database if not exists meta;GRANT SELECT ON meta.* TO 'orchestrator'@'%';"

- name: Create the meta.cluster table
  shell: mysql --defaults-file=/home/ubuntu/.my.cnf -e "CREATE TABLE IF NOT EXISTS cluster (anchor TINYINT NOT NULL, cluster_name VARCHAR(128) CHARSET ascii NOT NULL DEFAULT '', cluster_domain VARCHAR(128) CHARSET ascii NOT NULL DEFAULT '', PRIMARY KEY (anchor)) ENGINE=InnoDB DEFAULT CHARSET=utf8;" meta

- name: insert the cluster name in the meta.cluster table
  shell: mysql --defaults-file=/home/ubuntu/.my.cnf -e "insert ignore into cluster (anchor, cluster_name, cluster_domain) values (1,'lab','lab');" meta
