---
- name: Stop uneeded systemd services 
  systemd:
    state: stopped
    name: "{{ item.value }}"
  with_items:
          - value: container-getty@0
          - value: container-getty@1
          - value: container-getty@2
          - value: container-getty@3
          - value: systemd-resolved
  ignore_errors: True

- name: Remove the /etc/resolv.conf symlink
  file:
          path: /etc/resolv.conf
          state: absent

- name: Copy a valid resolv.conf file
  copy:
          src: resolv.conf
          dest: /etc/resolv.conf

- name: Copy the default sources.list file 
  copy:
          src: sources.list
          dest: /etc/apt/sources.list

- name: Copy the environment file 
  copy:
          src: environment
          dest: /etc/environment

- name: Copy the authorized_keys
  copy:
          src: authorized_keys
          dest: /home/ubuntu/authorized_keys
          owner: ubuntu 
          group: ubuntu
          mode: '0600'

- name: Build hosts file
  lineinfile: 
    dest: /etc/hosts 
    regexp: ".*{{ item }}$"
    line: "{{ hostvars[item].ansible_facts.eth0.ipv4.address }} {{item}}" 
    state: present
  when: hostvars[item].ansible_facts.eth0.ipv4.address is defined
  with_items: "{{ groups['all'] }}"

- name: Install debconf-utils
  apt:
    name: debconf-utils
    state: latest
    update_cache: yes

- name: Install gnupg 
  apt:
    name: gnupg
    state: latest

