- hosts: master
  become: yes
  tasks:
   - name: install kubectl
     apt:
       name: kubectl
       state: present

   - name: initialize the cluster
     shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
     args:
       chdir: $HOME
       creates: cluster_initialized.txt

   - name: Retrieve master join command
     shell: grep 'kubeadm join' $HOME/cluster_initialized.txt | sed 's/^ *//'
     register: joinCmd

   - name: Save join cmd locally
     local_action:
        module: copy
        content: "{{ joinCmd }}"
        dest: "./joinCmd.json"

   - name: create .kube directory
     become: yes
     become_user: ubuntu
     file:
       path: $HOME/.kube
       state: directory
       mode: 0755

   - name: copy admin.conf to user's kube config
     copy:
       src: /etc/kubernetes/admin.conf
       dest: /home/ubuntu/.kube/config
       remote_src: yes
       owner: ubuntu

   - name: Copy the flannel file
     copy: 
        src: kube-flannel.yml
        dest: /tmp/kube-flannel.yml
        mode: 0644

   - name: install Pod network
     become: yes
     become_user: ubuntu
     shell: kubectl apply -f /tmp/kube-flannel.yml >> pod_network_setup.txt
     args:
       chdir: $HOME
       creates: pod_network_setup.txt
